"""plaita.core.state — Distributed checkpoint schema.

Central registry of the magic-string keys ``ExecutionContext._context`` uses
for system state. Historical callers built these inline as
``f"{pfx}LAST_NODE"`` etc, scattering the key schema across runner.py /
executor.py / assignment.py / event/core.py — making any rename a multi-file
shotgun surgery and hiding how much actually lives in a checkpoint.

This module is the **single source of truth** for the checkpoint schema. Any
new system-state key MUST be added here (and to ``CHECKPOINT_KEYS``) before it
is written, otherwise it is not officially part of the contract and may be
dropped without a migration.

Why not a full Pydantic ``ExecutionState(BaseModel)``?
------------------------------------------------------
A real BaseModel rewrite would also have to:

1. Stay byte-for-byte compatible with the existing distributed checkpoint
   format (Redis/SQL persisted checkpoints must still load).
2. Tolerate unknown keys written by node plugins (``set_state("my_key", ...)``
   is a supported escape hatch for node-local state).
3. Round-trip cleanly through ``json.dumps`` for ``RedisStorage`` and through
   ``SQLAlchemy`` JSON columns.

Until that migration is done (a dedicated PR), this module at least makes the
**existing schema explicit** so future drift is caught at code review.
"""

from __future__ import annotations

from typing import Any, Dict, List


def _key(prefix: str, name: str) -> str:
    return f"{prefix}{name}"


class CheckpointSchema:
    """Schema definition for the distributed-checkpoint portion of ``_context``.

    A checkpoint key is one of:

    - A *system key*: pinned here in ``SYSTEM_KEY_NAMES``. These are written
      and read by core/runner code and survive ``to_dict`` / ``from_dict``.
    - An *expression key*: ``$INPUT`` / ``$NODE`` / ``$GLOBAL`` / ``$PARENT``
      / ``$ENV`` — prefix plus one of the configurable expression-namespace
      names. Names themselves live on ``ExecutionContext`` as
      ``express_input_name`` etc, so we only register the *static* suffixes
      here.
    - ``EXPRESS_PREFIX`` — the literal unprefixed key recording the prefix in
      use (so a checkpoint can be restored even if the prefix was customised).
    - *Node-local keys*: anything else. ``set_state("anything", ...)`` is
      allowed but **not part of the contract** — refactor or rename freely.
    """

    # System keys (prefixed by ``express_prefix``, default ``$``).
    SYSTEM_KEY_NAMES = (
        "LAST_NODE",     # most recently executed node id
        "BRANCH",        # branch taken by the most recent branching node
        "FLOW_ID",       # flow id of the currently executing flow
        "EXECUTION_ID",  # unique id for this execution (regenerated by clean())
    )

    # Unprefixed keys.
    BARE_KEY_NAMES = (
        "EXPRESS_PREFIX",  # records the prefix string so checkpoints can be restored
    )

    # Expression namespace names (the bit between ``$`` and the rest).
    EXPRESSION_NAMES = (
        "INPUT",
        "NODE",
        "GLOBAL",
        "PARENT",
        "ENV",
    )

    @classmethod
    def system_keys(cls, prefix: str = "$") -> List[str]:
        return [_key(prefix, n) for n in cls.SYSTEM_KEY_NAMES]

    @classmethod
    def bare_keys(cls) -> List[str]:
        return list(cls.BARE_KEY_NAMES)

    @classmethod
    def all_known_keys(cls, prefix: str = "$") -> List[str]:
        """Every key core owns. Used by ``validate_checkpoint`` for drift warnings."""
        return (
            cls.system_keys(prefix)
            + cls.bare_keys()
            + [_key(prefix, n) for n in cls.EXPRESSION_NAMES]
        )


def validate_checkpoint(data: Dict[str, Any], prefix: str = "$") -> List[str]:
    """Inspect a checkpoint dict and return a list of drift warnings.

    A *drift warning* is any key that looks like a system/expression key but
    is not in the official schema — usually a typo or a half-finished rename.
    Unknown node-local keys are NOT warnings (they are a supported escape
    hatch).

    Returns an empty list when the checkpoint is clean.
    """
    warnings: List[str] = []
    known = set(CheckpointSchema.all_known_keys(prefix))
    for k in data:
        if k in known or k in CheckpointSchema.bare_keys():
            continue
        # Looks like a system key (UPPER_CASE under prefix) but isn't registered?
        if k.startswith(prefix) and k[len(prefix):].isupper():
            warnings.append(
                f"checkpoint contains {k!r} which looks like a system key but is "
                f"not in CheckpointSchema; if it is meant to be system state, "
                f"register it in CheckpointSchema.SYSTEM_KEY_NAMES."
            )
    return warnings
